/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface Lab21Badge {
        /**
          * @default 'default'
         */
        "variant": 'default' | 'secondary' | 'outline';
    }
    interface Lab21Button {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default 'md'
         */
        "size": Lab21ButtonSize;
        /**
          * @default 'default'
         */
        "variant": Lab21ButtonVariant;
    }
    interface Lab21Card {
        /**
          * @default 'flat'
         */
        "elevation": 'flat' | 'raised';
    }
    interface Lab21Checkbox {
        /**
          * @default false
         */
        "checked": boolean;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default ''
         */
        "label": string;
    }
    interface Lab21Dialog {
        /**
          * @default ''
         */
        "heading": string;
        /**
          * @default false
         */
        "open": boolean;
        /**
          * @default this.open
         */
        "visible": boolean;
    }
    interface Lab21Input {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default ''
         */
        "label": string;
        /**
          * @default ''
         */
        "placeholder": string;
        /**
          * @default 'text'
         */
        "type": string;
        /**
          * @default ''
         */
        "value": string;
    }
    interface Lab21Progress {
        /**
          * @default 100
         */
        "max": number;
        /**
          * @default 0
         */
        "value": number;
    }
    interface Lab21RadioGroup {
        /**
          * @default ''
         */
        "fieldLabel": string;
        /**
          * @default 'lab21-radio'
         */
        "name": string;
        /**
          * @default []
         */
        "options": string | string[];
        /**
          * @default ''
         */
        "value": string;
    }
    interface Lab21Select {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default ''
         */
        "fieldLabel": string;
        /**
          * @default []
         */
        "options": string | string[];
        /**
          * @default 'Select...'
         */
        "placeholder": string;
        /**
          * @default ''
         */
        "value": string;
    }
    interface Lab21Slider {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default 100
         */
        "max": number;
        /**
          * @default 0
         */
        "min": number;
        /**
          * @default 1
         */
        "step": number;
        /**
          * @default 0
         */
        "value": number;
    }
    interface Lab21Switch {
        /**
          * @default false
         */
        "checked": boolean;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default ''
         */
        "label": string;
    }
    interface Lab21Tabs {
        /**
          * @default ''
         */
        "defaultValue": string;
        /**
          * @default ''
         */
        "value": string;
    }
}
export interface Lab21CheckboxCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLLab21CheckboxElement;
}
export interface Lab21DialogCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLLab21DialogElement;
}
export interface Lab21RadioGroupCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLLab21RadioGroupElement;
}
export interface Lab21SelectCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLLab21SelectElement;
}
export interface Lab21SliderCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLLab21SliderElement;
}
export interface Lab21SwitchCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLLab21SwitchElement;
}
export interface Lab21TabsCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLLab21TabsElement;
}
declare global {
    interface HTMLLab21BadgeElement extends Components.Lab21Badge, HTMLStencilElement {
    }
    var HTMLLab21BadgeElement: {
        prototype: HTMLLab21BadgeElement;
        new (): HTMLLab21BadgeElement;
    };
    interface HTMLLab21ButtonElement extends Components.Lab21Button, HTMLStencilElement {
    }
    var HTMLLab21ButtonElement: {
        prototype: HTMLLab21ButtonElement;
        new (): HTMLLab21ButtonElement;
    };
    interface HTMLLab21CardElement extends Components.Lab21Card, HTMLStencilElement {
    }
    var HTMLLab21CardElement: {
        prototype: HTMLLab21CardElement;
        new (): HTMLLab21CardElement;
    };
    interface HTMLLab21CheckboxElementEventMap {
        "lab21Change": boolean;
    }
    interface HTMLLab21CheckboxElement extends Components.Lab21Checkbox, HTMLStencilElement {
        addEventListener<K extends keyof HTMLLab21CheckboxElementEventMap>(type: K, listener: (this: HTMLLab21CheckboxElement, ev: Lab21CheckboxCustomEvent<HTMLLab21CheckboxElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLLab21CheckboxElementEventMap>(type: K, listener: (this: HTMLLab21CheckboxElement, ev: Lab21CheckboxCustomEvent<HTMLLab21CheckboxElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLLab21CheckboxElement: {
        prototype: HTMLLab21CheckboxElement;
        new (): HTMLLab21CheckboxElement;
    };
    interface HTMLLab21DialogElementEventMap {
        "lab21Close": void;
    }
    interface HTMLLab21DialogElement extends Components.Lab21Dialog, HTMLStencilElement {
        addEventListener<K extends keyof HTMLLab21DialogElementEventMap>(type: K, listener: (this: HTMLLab21DialogElement, ev: Lab21DialogCustomEvent<HTMLLab21DialogElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLLab21DialogElementEventMap>(type: K, listener: (this: HTMLLab21DialogElement, ev: Lab21DialogCustomEvent<HTMLLab21DialogElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLLab21DialogElement: {
        prototype: HTMLLab21DialogElement;
        new (): HTMLLab21DialogElement;
    };
    interface HTMLLab21InputElement extends Components.Lab21Input, HTMLStencilElement {
    }
    var HTMLLab21InputElement: {
        prototype: HTMLLab21InputElement;
        new (): HTMLLab21InputElement;
    };
    interface HTMLLab21ProgressElement extends Components.Lab21Progress, HTMLStencilElement {
    }
    var HTMLLab21ProgressElement: {
        prototype: HTMLLab21ProgressElement;
        new (): HTMLLab21ProgressElement;
    };
    interface HTMLLab21RadioGroupElementEventMap {
        "lab21Change": string;
    }
    interface HTMLLab21RadioGroupElement extends Components.Lab21RadioGroup, HTMLStencilElement {
        addEventListener<K extends keyof HTMLLab21RadioGroupElementEventMap>(type: K, listener: (this: HTMLLab21RadioGroupElement, ev: Lab21RadioGroupCustomEvent<HTMLLab21RadioGroupElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLLab21RadioGroupElementEventMap>(type: K, listener: (this: HTMLLab21RadioGroupElement, ev: Lab21RadioGroupCustomEvent<HTMLLab21RadioGroupElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLLab21RadioGroupElement: {
        prototype: HTMLLab21RadioGroupElement;
        new (): HTMLLab21RadioGroupElement;
    };
    interface HTMLLab21SelectElementEventMap {
        "lab21Change": string;
    }
    interface HTMLLab21SelectElement extends Components.Lab21Select, HTMLStencilElement {
        addEventListener<K extends keyof HTMLLab21SelectElementEventMap>(type: K, listener: (this: HTMLLab21SelectElement, ev: Lab21SelectCustomEvent<HTMLLab21SelectElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLLab21SelectElementEventMap>(type: K, listener: (this: HTMLLab21SelectElement, ev: Lab21SelectCustomEvent<HTMLLab21SelectElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLLab21SelectElement: {
        prototype: HTMLLab21SelectElement;
        new (): HTMLLab21SelectElement;
    };
    interface HTMLLab21SliderElementEventMap {
        "lab21Change": number;
    }
    interface HTMLLab21SliderElement extends Components.Lab21Slider, HTMLStencilElement {
        addEventListener<K extends keyof HTMLLab21SliderElementEventMap>(type: K, listener: (this: HTMLLab21SliderElement, ev: Lab21SliderCustomEvent<HTMLLab21SliderElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLLab21SliderElementEventMap>(type: K, listener: (this: HTMLLab21SliderElement, ev: Lab21SliderCustomEvent<HTMLLab21SliderElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLLab21SliderElement: {
        prototype: HTMLLab21SliderElement;
        new (): HTMLLab21SliderElement;
    };
    interface HTMLLab21SwitchElementEventMap {
        "lab21Change": boolean;
    }
    interface HTMLLab21SwitchElement extends Components.Lab21Switch, HTMLStencilElement {
        addEventListener<K extends keyof HTMLLab21SwitchElementEventMap>(type: K, listener: (this: HTMLLab21SwitchElement, ev: Lab21SwitchCustomEvent<HTMLLab21SwitchElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLLab21SwitchElementEventMap>(type: K, listener: (this: HTMLLab21SwitchElement, ev: Lab21SwitchCustomEvent<HTMLLab21SwitchElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLLab21SwitchElement: {
        prototype: HTMLLab21SwitchElement;
        new (): HTMLLab21SwitchElement;
    };
    interface HTMLLab21TabsElementEventMap {
        "lab21Change": string;
    }
    interface HTMLLab21TabsElement extends Components.Lab21Tabs, HTMLStencilElement {
        addEventListener<K extends keyof HTMLLab21TabsElementEventMap>(type: K, listener: (this: HTMLLab21TabsElement, ev: Lab21TabsCustomEvent<HTMLLab21TabsElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLLab21TabsElementEventMap>(type: K, listener: (this: HTMLLab21TabsElement, ev: Lab21TabsCustomEvent<HTMLLab21TabsElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLLab21TabsElement: {
        prototype: HTMLLab21TabsElement;
        new (): HTMLLab21TabsElement;
    };
    interface HTMLElementTagNameMap {
        "lab21-badge": HTMLLab21BadgeElement;
        "lab21-button": HTMLLab21ButtonElement;
        "lab21-card": HTMLLab21CardElement;
        "lab21-checkbox": HTMLLab21CheckboxElement;
        "lab21-dialog": HTMLLab21DialogElement;
        "lab21-input": HTMLLab21InputElement;
        "lab21-progress": HTMLLab21ProgressElement;
        "lab21-radio-group": HTMLLab21RadioGroupElement;
        "lab21-select": HTMLLab21SelectElement;
        "lab21-slider": HTMLLab21SliderElement;
        "lab21-switch": HTMLLab21SwitchElement;
        "lab21-tabs": HTMLLab21TabsElement;
    }
}
declare namespace LocalJSX {
    interface Lab21Badge {
        /**
          * @default 'default'
         */
        "variant"?: 'default' | 'secondary' | 'outline';
    }
    interface Lab21Button {
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default 'md'
         */
        "size"?: Lab21ButtonSize;
        /**
          * @default 'default'
         */
        "variant"?: Lab21ButtonVariant;
    }
    interface Lab21Card {
        /**
          * @default 'flat'
         */
        "elevation"?: 'flat' | 'raised';
    }
    interface Lab21Checkbox {
        /**
          * @default false
         */
        "checked"?: boolean;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default ''
         */
        "label"?: string;
        "onLab21Change"?: (event: Lab21CheckboxCustomEvent<boolean>) => void;
    }
    interface Lab21Dialog {
        /**
          * @default ''
         */
        "heading"?: string;
        "onLab21Close"?: (event: Lab21DialogCustomEvent<void>) => void;
        /**
          * @default false
         */
        "open"?: boolean;
        /**
          * @default this.open
         */
        "visible"?: boolean;
    }
    interface Lab21Input {
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default ''
         */
        "label"?: string;
        /**
          * @default ''
         */
        "placeholder"?: string;
        /**
          * @default 'text'
         */
        "type"?: string;
        /**
          * @default ''
         */
        "value"?: string;
    }
    interface Lab21Progress {
        /**
          * @default 100
         */
        "max"?: number;
        /**
          * @default 0
         */
        "value"?: number;
    }
    interface Lab21RadioGroup {
        /**
          * @default ''
         */
        "fieldLabel"?: string;
        /**
          * @default 'lab21-radio'
         */
        "name"?: string;
        "onLab21Change"?: (event: Lab21RadioGroupCustomEvent<string>) => void;
        /**
          * @default []
         */
        "options"?: string | string[];
        /**
          * @default ''
         */
        "value"?: string;
    }
    interface Lab21Select {
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default ''
         */
        "fieldLabel"?: string;
        "onLab21Change"?: (event: Lab21SelectCustomEvent<string>) => void;
        /**
          * @default []
         */
        "options"?: string | string[];
        /**
          * @default 'Select...'
         */
        "placeholder"?: string;
        /**
          * @default ''
         */
        "value"?: string;
    }
    interface Lab21Slider {
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default 100
         */
        "max"?: number;
        /**
          * @default 0
         */
        "min"?: number;
        "onLab21Change"?: (event: Lab21SliderCustomEvent<number>) => void;
        /**
          * @default 1
         */
        "step"?: number;
        /**
          * @default 0
         */
        "value"?: number;
    }
    interface Lab21Switch {
        /**
          * @default false
         */
        "checked"?: boolean;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default ''
         */
        "label"?: string;
        "onLab21Change"?: (event: Lab21SwitchCustomEvent<boolean>) => void;
    }
    interface Lab21Tabs {
        /**
          * @default ''
         */
        "defaultValue"?: string;
        "onLab21Change"?: (event: Lab21TabsCustomEvent<string>) => void;
        /**
          * @default ''
         */
        "value"?: string;
    }

    interface Lab21BadgeAttributes {
        "variant": 'default' | 'secondary' | 'outline';
    }
    interface Lab21ButtonAttributes {
        "variant": Lab21ButtonVariant;
        "size": Lab21ButtonSize;
        "disabled": boolean;
    }
    interface Lab21CardAttributes {
        "elevation": 'flat' | 'raised';
    }
    interface Lab21CheckboxAttributes {
        "checked": boolean;
        "disabled": boolean;
        "label": string;
    }
    interface Lab21DialogAttributes {
        "open": boolean;
        "heading": string;
        "visible": boolean;
    }
    interface Lab21InputAttributes {
        "type": string;
        "placeholder": string;
        "value": string;
        "disabled": boolean;
        "label": string;
    }
    interface Lab21ProgressAttributes {
        "value": number;
        "max": number;
    }
    interface Lab21RadioGroupAttributes {
        "value": string;
        "name": string;
        "options": string | string[];
        "fieldLabel": string;
    }
    interface Lab21SelectAttributes {
        "value": string;
        "options": string | string[];
        "placeholder": string;
        "disabled": boolean;
        "fieldLabel": string;
    }
    interface Lab21SliderAttributes {
        "value": number;
        "min": number;
        "max": number;
        "step": number;
        "disabled": boolean;
    }
    interface Lab21SwitchAttributes {
        "checked": boolean;
        "disabled": boolean;
        "label": string;
    }
    interface Lab21TabsAttributes {
        "defaultValue": string;
        "value": string;
    }

    interface IntrinsicElements {
        "lab21-badge": Omit<Lab21Badge, keyof Lab21BadgeAttributes> & { [K in keyof Lab21Badge & keyof Lab21BadgeAttributes]?: Lab21Badge[K] } & { [K in keyof Lab21Badge & keyof Lab21BadgeAttributes as `attr:${K}`]?: Lab21BadgeAttributes[K] } & { [K in keyof Lab21Badge & keyof Lab21BadgeAttributes as `prop:${K}`]?: Lab21Badge[K] };
        "lab21-button": Omit<Lab21Button, keyof Lab21ButtonAttributes> & { [K in keyof Lab21Button & keyof Lab21ButtonAttributes]?: Lab21Button[K] } & { [K in keyof Lab21Button & keyof Lab21ButtonAttributes as `attr:${K}`]?: Lab21ButtonAttributes[K] } & { [K in keyof Lab21Button & keyof Lab21ButtonAttributes as `prop:${K}`]?: Lab21Button[K] };
        "lab21-card": Omit<Lab21Card, keyof Lab21CardAttributes> & { [K in keyof Lab21Card & keyof Lab21CardAttributes]?: Lab21Card[K] } & { [K in keyof Lab21Card & keyof Lab21CardAttributes as `attr:${K}`]?: Lab21CardAttributes[K] } & { [K in keyof Lab21Card & keyof Lab21CardAttributes as `prop:${K}`]?: Lab21Card[K] };
        "lab21-checkbox": Omit<Lab21Checkbox, keyof Lab21CheckboxAttributes> & { [K in keyof Lab21Checkbox & keyof Lab21CheckboxAttributes]?: Lab21Checkbox[K] } & { [K in keyof Lab21Checkbox & keyof Lab21CheckboxAttributes as `attr:${K}`]?: Lab21CheckboxAttributes[K] } & { [K in keyof Lab21Checkbox & keyof Lab21CheckboxAttributes as `prop:${K}`]?: Lab21Checkbox[K] };
        "lab21-dialog": Omit<Lab21Dialog, keyof Lab21DialogAttributes> & { [K in keyof Lab21Dialog & keyof Lab21DialogAttributes]?: Lab21Dialog[K] } & { [K in keyof Lab21Dialog & keyof Lab21DialogAttributes as `attr:${K}`]?: Lab21DialogAttributes[K] } & { [K in keyof Lab21Dialog & keyof Lab21DialogAttributes as `prop:${K}`]?: Lab21Dialog[K] };
        "lab21-input": Omit<Lab21Input, keyof Lab21InputAttributes> & { [K in keyof Lab21Input & keyof Lab21InputAttributes]?: Lab21Input[K] } & { [K in keyof Lab21Input & keyof Lab21InputAttributes as `attr:${K}`]?: Lab21InputAttributes[K] } & { [K in keyof Lab21Input & keyof Lab21InputAttributes as `prop:${K}`]?: Lab21Input[K] };
        "lab21-progress": Omit<Lab21Progress, keyof Lab21ProgressAttributes> & { [K in keyof Lab21Progress & keyof Lab21ProgressAttributes]?: Lab21Progress[K] } & { [K in keyof Lab21Progress & keyof Lab21ProgressAttributes as `attr:${K}`]?: Lab21ProgressAttributes[K] } & { [K in keyof Lab21Progress & keyof Lab21ProgressAttributes as `prop:${K}`]?: Lab21Progress[K] };
        "lab21-radio-group": Omit<Lab21RadioGroup, keyof Lab21RadioGroupAttributes> & { [K in keyof Lab21RadioGroup & keyof Lab21RadioGroupAttributes]?: Lab21RadioGroup[K] } & { [K in keyof Lab21RadioGroup & keyof Lab21RadioGroupAttributes as `attr:${K}`]?: Lab21RadioGroupAttributes[K] } & { [K in keyof Lab21RadioGroup & keyof Lab21RadioGroupAttributes as `prop:${K}`]?: Lab21RadioGroup[K] };
        "lab21-select": Omit<Lab21Select, keyof Lab21SelectAttributes> & { [K in keyof Lab21Select & keyof Lab21SelectAttributes]?: Lab21Select[K] } & { [K in keyof Lab21Select & keyof Lab21SelectAttributes as `attr:${K}`]?: Lab21SelectAttributes[K] } & { [K in keyof Lab21Select & keyof Lab21SelectAttributes as `prop:${K}`]?: Lab21Select[K] };
        "lab21-slider": Omit<Lab21Slider, keyof Lab21SliderAttributes> & { [K in keyof Lab21Slider & keyof Lab21SliderAttributes]?: Lab21Slider[K] } & { [K in keyof Lab21Slider & keyof Lab21SliderAttributes as `attr:${K}`]?: Lab21SliderAttributes[K] } & { [K in keyof Lab21Slider & keyof Lab21SliderAttributes as `prop:${K}`]?: Lab21Slider[K] };
        "lab21-switch": Omit<Lab21Switch, keyof Lab21SwitchAttributes> & { [K in keyof Lab21Switch & keyof Lab21SwitchAttributes]?: Lab21Switch[K] } & { [K in keyof Lab21Switch & keyof Lab21SwitchAttributes as `attr:${K}`]?: Lab21SwitchAttributes[K] } & { [K in keyof Lab21Switch & keyof Lab21SwitchAttributes as `prop:${K}`]?: Lab21Switch[K] };
        "lab21-tabs": Omit<Lab21Tabs, keyof Lab21TabsAttributes> & { [K in keyof Lab21Tabs & keyof Lab21TabsAttributes]?: Lab21Tabs[K] } & { [K in keyof Lab21Tabs & keyof Lab21TabsAttributes as `attr:${K}`]?: Lab21TabsAttributes[K] } & { [K in keyof Lab21Tabs & keyof Lab21TabsAttributes as `prop:${K}`]?: Lab21Tabs[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "lab21-badge": LocalJSX.IntrinsicElements["lab21-badge"] & JSXBase.HTMLAttributes<HTMLLab21BadgeElement>;
            "lab21-button": LocalJSX.IntrinsicElements["lab21-button"] & JSXBase.HTMLAttributes<HTMLLab21ButtonElement>;
            "lab21-card": LocalJSX.IntrinsicElements["lab21-card"] & JSXBase.HTMLAttributes<HTMLLab21CardElement>;
            "lab21-checkbox": LocalJSX.IntrinsicElements["lab21-checkbox"] & JSXBase.HTMLAttributes<HTMLLab21CheckboxElement>;
            "lab21-dialog": LocalJSX.IntrinsicElements["lab21-dialog"] & JSXBase.HTMLAttributes<HTMLLab21DialogElement>;
            "lab21-input": LocalJSX.IntrinsicElements["lab21-input"] & JSXBase.HTMLAttributes<HTMLLab21InputElement>;
            "lab21-progress": LocalJSX.IntrinsicElements["lab21-progress"] & JSXBase.HTMLAttributes<HTMLLab21ProgressElement>;
            "lab21-radio-group": LocalJSX.IntrinsicElements["lab21-radio-group"] & JSXBase.HTMLAttributes<HTMLLab21RadioGroupElement>;
            "lab21-select": LocalJSX.IntrinsicElements["lab21-select"] & JSXBase.HTMLAttributes<HTMLLab21SelectElement>;
            "lab21-slider": LocalJSX.IntrinsicElements["lab21-slider"] & JSXBase.HTMLAttributes<HTMLLab21SliderElement>;
            "lab21-switch": LocalJSX.IntrinsicElements["lab21-switch"] & JSXBase.HTMLAttributes<HTMLLab21SwitchElement>;
            "lab21-tabs": LocalJSX.IntrinsicElements["lab21-tabs"] & JSXBase.HTMLAttributes<HTMLLab21TabsElement>;
        }
    }
}
