'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type Lab21CheckboxCustomEvent, type Lab21DialogCustomEvent, type Lab21RadioGroupCustomEvent, type Lab21SelectCustomEvent, type Lab21SliderCustomEvent, type Lab21SwitchCustomEvent, type Lab21TabsCustomEvent } from "@lab21/core";
import type { Components } from "@lab21/core/dist/components";
import { Lab21Badge as Lab21BadgeElement, defineCustomElement as defineLab21Badge } from "@lab21/core/dist/components/lab21-badge.js";
import { Lab21Button as Lab21ButtonElement, defineCustomElement as defineLab21Button } from "@lab21/core/dist/components/lab21-button.js";
import { Lab21Card as Lab21CardElement, defineCustomElement as defineLab21Card } from "@lab21/core/dist/components/lab21-card.js";
import { Lab21Checkbox as Lab21CheckboxElement, defineCustomElement as defineLab21Checkbox } from "@lab21/core/dist/components/lab21-checkbox.js";
import { Lab21Dialog as Lab21DialogElement, defineCustomElement as defineLab21Dialog } from "@lab21/core/dist/components/lab21-dialog.js";
import { Lab21Input as Lab21InputElement, defineCustomElement as defineLab21Input } from "@lab21/core/dist/components/lab21-input.js";
import { Lab21Progress as Lab21ProgressElement, defineCustomElement as defineLab21Progress } from "@lab21/core/dist/components/lab21-progress.js";
import { Lab21RadioGroup as Lab21RadioGroupElement, defineCustomElement as defineLab21RadioGroup } from "@lab21/core/dist/components/lab21-radio-group.js";
import { Lab21Select as Lab21SelectElement, defineCustomElement as defineLab21Select } from "@lab21/core/dist/components/lab21-select.js";
import { Lab21Slider as Lab21SliderElement, defineCustomElement as defineLab21Slider } from "@lab21/core/dist/components/lab21-slider.js";
import { Lab21Switch as Lab21SwitchElement, defineCustomElement as defineLab21Switch } from "@lab21/core/dist/components/lab21-switch.js";
import { Lab21Tabs as Lab21TabsElement, defineCustomElement as defineLab21Tabs } from "@lab21/core/dist/components/lab21-tabs.js";

export type Lab21BadgeEvents = NonNullable<unknown>;

export const Lab21Badge: StencilReactComponent<Lab21BadgeElement, Lab21BadgeEvents, Components.Lab21Badge> = /*@__PURE__*/ createComponent<Lab21BadgeElement, Lab21BadgeEvents, Components.Lab21Badge>({
    tagName: 'lab21-badge',
    elementClass: Lab21BadgeElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as Lab21BadgeEvents,
    defineCustomElement: defineLab21Badge
});

export type Lab21ButtonEvents = NonNullable<unknown>;

export const Lab21Button: StencilReactComponent<Lab21ButtonElement, Lab21ButtonEvents, Components.Lab21Button> = /*@__PURE__*/ createComponent<Lab21ButtonElement, Lab21ButtonEvents, Components.Lab21Button>({
    tagName: 'lab21-button',
    elementClass: Lab21ButtonElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as Lab21ButtonEvents,
    defineCustomElement: defineLab21Button
});

export type Lab21CardEvents = NonNullable<unknown>;

export const Lab21Card: StencilReactComponent<Lab21CardElement, Lab21CardEvents, Components.Lab21Card> = /*@__PURE__*/ createComponent<Lab21CardElement, Lab21CardEvents, Components.Lab21Card>({
    tagName: 'lab21-card',
    elementClass: Lab21CardElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as Lab21CardEvents,
    defineCustomElement: defineLab21Card
});

export type Lab21CheckboxEvents = { onLab21Change: EventName<Lab21CheckboxCustomEvent<boolean>> };

export const Lab21Checkbox: StencilReactComponent<Lab21CheckboxElement, Lab21CheckboxEvents, Components.Lab21Checkbox> = /*@__PURE__*/ createComponent<Lab21CheckboxElement, Lab21CheckboxEvents, Components.Lab21Checkbox>({
    tagName: 'lab21-checkbox',
    elementClass: Lab21CheckboxElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onLab21Change: 'lab21Change' } as Lab21CheckboxEvents,
    defineCustomElement: defineLab21Checkbox
});

export type Lab21DialogEvents = { onLab21Close: EventName<Lab21DialogCustomEvent<void>> };

export const Lab21Dialog: StencilReactComponent<Lab21DialogElement, Lab21DialogEvents, Components.Lab21Dialog> = /*@__PURE__*/ createComponent<Lab21DialogElement, Lab21DialogEvents, Components.Lab21Dialog>({
    tagName: 'lab21-dialog',
    elementClass: Lab21DialogElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onLab21Close: 'lab21Close' } as Lab21DialogEvents,
    defineCustomElement: defineLab21Dialog
});

export type Lab21InputEvents = NonNullable<unknown>;

export const Lab21Input: StencilReactComponent<Lab21InputElement, Lab21InputEvents, Components.Lab21Input> = /*@__PURE__*/ createComponent<Lab21InputElement, Lab21InputEvents, Components.Lab21Input>({
    tagName: 'lab21-input',
    elementClass: Lab21InputElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as Lab21InputEvents,
    defineCustomElement: defineLab21Input
});

export type Lab21ProgressEvents = NonNullable<unknown>;

export const Lab21Progress: StencilReactComponent<Lab21ProgressElement, Lab21ProgressEvents, Components.Lab21Progress> = /*@__PURE__*/ createComponent<Lab21ProgressElement, Lab21ProgressEvents, Components.Lab21Progress>({
    tagName: 'lab21-progress',
    elementClass: Lab21ProgressElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as Lab21ProgressEvents,
    defineCustomElement: defineLab21Progress
});

export type Lab21RadioGroupEvents = { onLab21Change: EventName<Lab21RadioGroupCustomEvent<string>> };

export const Lab21RadioGroup: StencilReactComponent<Lab21RadioGroupElement, Lab21RadioGroupEvents, Components.Lab21RadioGroup> = /*@__PURE__*/ createComponent<Lab21RadioGroupElement, Lab21RadioGroupEvents, Components.Lab21RadioGroup>({
    tagName: 'lab21-radio-group',
    elementClass: Lab21RadioGroupElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onLab21Change: 'lab21Change' } as Lab21RadioGroupEvents,
    defineCustomElement: defineLab21RadioGroup
});

export type Lab21SelectEvents = { onLab21Change: EventName<Lab21SelectCustomEvent<string>> };

export const Lab21Select: StencilReactComponent<Lab21SelectElement, Lab21SelectEvents, Components.Lab21Select> = /*@__PURE__*/ createComponent<Lab21SelectElement, Lab21SelectEvents, Components.Lab21Select>({
    tagName: 'lab21-select',
    elementClass: Lab21SelectElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onLab21Change: 'lab21Change' } as Lab21SelectEvents,
    defineCustomElement: defineLab21Select
});

export type Lab21SliderEvents = { onLab21Change: EventName<Lab21SliderCustomEvent<number>> };

export const Lab21Slider: StencilReactComponent<Lab21SliderElement, Lab21SliderEvents, Components.Lab21Slider> = /*@__PURE__*/ createComponent<Lab21SliderElement, Lab21SliderEvents, Components.Lab21Slider>({
    tagName: 'lab21-slider',
    elementClass: Lab21SliderElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onLab21Change: 'lab21Change' } as Lab21SliderEvents,
    defineCustomElement: defineLab21Slider
});

export type Lab21SwitchEvents = { onLab21Change: EventName<Lab21SwitchCustomEvent<boolean>> };

export const Lab21Switch: StencilReactComponent<Lab21SwitchElement, Lab21SwitchEvents, Components.Lab21Switch> = /*@__PURE__*/ createComponent<Lab21SwitchElement, Lab21SwitchEvents, Components.Lab21Switch>({
    tagName: 'lab21-switch',
    elementClass: Lab21SwitchElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onLab21Change: 'lab21Change' } as Lab21SwitchEvents,
    defineCustomElement: defineLab21Switch
});

export type Lab21TabsEvents = { onLab21Change: EventName<Lab21TabsCustomEvent<string>> };

export const Lab21Tabs: StencilReactComponent<Lab21TabsElement, Lab21TabsEvents, Components.Lab21Tabs> = /*@__PURE__*/ createComponent<Lab21TabsElement, Lab21TabsEvents, Components.Lab21Tabs>({
    tagName: 'lab21-tabs',
    elementClass: Lab21TabsElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onLab21Change: 'lab21Change' } as Lab21TabsEvents,
    defineCustomElement: defineLab21Tabs
});
