const fs = require('fs');
const path = require('path');

const htmlPath = path.join(__dirname, '../esp32/index.html');
const cssPath = path.join(__dirname, '../esp32/lab-esp.css');
const outPath = path.join(__dirname, '../esp32/WebUI.h');

if (!fs.existsSync(htmlPath)) {
    console.error("esp32/index.html not found. Please create it first.");
    process.exit(1);
}

const html = fs.readFileSync(htmlPath, 'utf-8');
const css = fs.readFileSync(cssPath, 'utf-8');

// Micro-minify CSS (removes spaces, newlines, and comments)
const minCss = css.replace(/\s+/g, ' ').replace(/\/\*[\s\S]*?\*\//g, '');

// Inject CSS into HTML
const inlinedHtml = html.replace('<!-- INJECT_CSS -->', `<style>${minCss}</style>`);

// Micro-minify HTML (remove excessive spaces between tags)
const minHtml = inlinedHtml.replace(/\n\s+/g, '\n').trim();

// Generate C++ Header File
const headerContent = `// Auto-generated by Lab21 CI/CD ESP32 Builder
#ifndef LAB21_WEB_UI_H
#define LAB21_WEB_UI_H

#include <Arduino.h>

// UI Size: ${Buffer.byteLength(minHtml, 'utf8')} bytes
// Architecture: Native HTML5 + Micro CSS + Alpine.js
const char index_html[] PROGMEM = R"rawliteral(
${minHtml}
)rawliteral";

#endif
`;

fs.writeFileSync(outPath, headerContent);
console.log(`[Lab21 CI/CD] Successfully generated esp32/WebUI.h (${Buffer.byteLength(minHtml, 'utf8')} bytes)`);
